import type {
  AuditRow,
  CaregiverRow,
  ContributionRow,
  ContributorDetail,
  ContributorRow,
  DemandRow,
  DuplicateCandidate,
  FlagRow,
  FoundingRow,
  Overview,
  PendingOptionRow,
  RestrictedNote,
} from "./types";

/**
 * Sample rows for reviewing the admin before the backend exists.
 *
 * Only ever served when the n8n hook is unconfigured **and** the page explicitly asks
 * for it, and every page that shows them displays a banner saying so. Names are
 * obviously invented on purpose — nothing here should be mistakable for a real
 * contributor.
 *
 * They double as shape documentation: if `admin_read` returns these keys, the pages
 * render.
 */

const now = "2026-07-30T10:00:00.000Z";

export const sampleOverview: Overview = {
  contributors: { total: 42, completed: 31, with_two_plus: 19 },
  submissions: { activities: 58, caregivers: 11, places: 22, tips: 14 },
  consent: { follow_up_opt_in: 27, reference_willing: 8 },
  caregivers: { mentioned: 6, invited: 3, consented: 2, declined: 0 },
  quality: { low_confidence: 5, open_flags: 2, pending_options: 9, review_holds: 2 },
  founding: { pending: 12, approved: 19 },
  demand: { ordinary: 14, peer_support: 3, high_stakes: 1 },
  drop_off: [
    { step: "Opened the link", reached: 64 },
    { step: "Started the profile", reached: 48 },
    { step: "Finished the profile", reached: 39 },
    { step: "Confirmed their number", reached: 35 },
    { step: "Shared one card", reached: 33 },
    { step: "Shared two or more", reached: 19 },
    { step: "Finished", reached: 31 },
  ],
  posthog_url: null,
};

export const sampleContributors: ContributorRow[] = [
  {
    id: "c1",
    name: "Sample Parent A",
    phone_masked: "••• ••• 4821",
    neighborhood: "south-pasadena",
    child_birth_years: [2023, 2020],
    submissions: 4,
    qualifying_approved: 3,
    founding_status: "founding",
    follow_up_opt_in: true,
    wants_founding: true,
    is_test: false,
    created_at: now,
  },
  {
    id: "c2",
    name: "Sample Parent B",
    phone_masked: "••• ••• 0093",
    neighborhood: "altadena",
    child_birth_years: [2019],
    submissions: 2,
    qualifying_approved: 1,
    founding_status: "pending_founding",
    follow_up_opt_in: true,
    wants_founding: true,
    is_test: false,
    created_at: now,
  },
  {
    id: "c3",
    name: null,
    phone_masked: null,
    neighborhood: "bungalow-heaven",
    child_birth_years: [2025],
    submissions: 1,
    qualifying_approved: 0,
    founding_status: "none",
    follow_up_opt_in: null,
    /** The anonymous path: welcome, labelled, not eligible for founding. */
    wants_founding: false,
    is_test: false,
    created_at: now,
  },
  {
    id: "c4",
    name: "QA Walkthrough",
    phone_masked: "••• ••• 0000",
    neighborhood: "old-pasadena",
    child_birth_years: [2021],
    submissions: 3,
    qualifying_approved: 0,
    founding_status: "pending_founding",
    follow_up_opt_in: false,
    wants_founding: true,
    is_test: true,
    created_at: now,
  },
];

export const sampleContributorDetail: ContributorDetail = {
  ...sampleContributors[0],
  invite_code: "sgv-founding",
  source: "link",
  profile_completeness: 92,
  time_in_area: "3_10_years",
  moved_from: null,
  attribution: "first_name_safe",
  aggregate_display: true,
  monthly_contact_allowance: 3,
  allowance_mode: "fixed",
  topic_preferences: ["camps", "preschools_schools", "babysitters"],
  topics_lived_experience: ["sleep_routines", "returning_to_work"],
  school_status: { "walden-school": "current", "the-growing-place": "former" },
  affinities: [
    { affinity_type: "school", affinity_value: "walden-school", weight: 5 },
    { affinity_type: "activity", affinity_value: "music-together", weight: 4 },
    { affinity_type: "neighborhood", affinity_value: "south-pasadena", weight: 3 },
  ],
  relevance: [
    { dimension: "budget", value: "compare_value" },
    { dimension: "logistics", value: "close_to_home" },
    { dimension: "childcare", value: "nanny_or_sitter" },
    { dimension: "tenure", value: "3_10_years" },
  ],
  cards: [
    {
      id: "s1",
      kind: "activity",
      title: "Little Maestros",
      status: "approved",
      firsthand: true,
      created_at: now,
    },
    {
      id: "s2",
      kind: "caregiver",
      title: "Rosa R.",
      status: "pending_review",
      firsthand: true,
      created_at: now,
    },
    {
      id: "s3",
      kind: "place",
      title: "Victory Park playground",
      status: "approved",
      firsthand: false,
      created_at: now,
    },
  ],
  consents: [
    {
      scope: "sms",
      status: "opted_in",
      text_version: "seed-sms-2026-08-01",
      captured_at: now,
    },
    {
      scope: "follow_up",
      status: "opted_in",
      text_version: "seed-followup-2026-07-31",
      captured_at: now,
    },
  ],
  transcript: [
    { role: "pando", text: "What would you like to share?", at: now },
    { role: "parent", text: "An activity or class", at: now },
  ],
  notes: [
    {
      id: "n1",
      author: "janet",
      body: "Knows every family at Field — good reference candidate.",
      at: now,
    },
  ],
};

export const sampleContributions: ContributionRow[] = [
  {
    id: "a1",
    kind: "activity",
    place: {
      id: "p1",
      name: "Little Maestros",
      venue: "on Mission Ave",
      neighborhoods: ["south-pasadena"],
      age_bands: ["toddler", "preschool"],
      freshness_state: "fresh",
      last_confirmed_at: now,
      validated_count: 3,
    },
    firsthand: true,
    child_age_at_time: [2],
    last_there: "current",
    how_much: "a_term",
    recommendation: "yes",
    what_makes_it_great: "Small groups, and the teacher is unbelievably patient.",
    caveat: "Saturdays get packed — book the 9am.",
    caveat_answered: true,
    who_for: "A cautious toddler who warms up slowly",
    who_not_for: "Not for a kid who needs a lot of structure",
    price_band: "50_100",
    price_unit: "per_month",
    worth_it: "great_value",
    follow_up_ok: true,
    tip_text: null,
    status: "pending_review",
    confidence: 0.91,
    provenance: "parent_submitted",
    contributor: { id: "c1", name: "Sample Parent A" },
    is_test: false,
    created_at: now,
  },
  {
    id: "a2",
    kind: "activity",
    place: {
      id: "p2",
      name: "Rose Bowl Aquatics parent & me",
      venue: null,
      neighborhoods: ["old-pasadena"],
      age_bands: ["baby", "toddler"],
      freshness_state: "ageing",
      last_confirmed_at: "2026-01-12T10:00:00.000Z",
      validated_count: 1,
    },
    /** Secondhand: welcome, labelled, and never counted toward Founding. */
    firsthand: false,
    child_age_at_time: [1],
    last_there: "over_year",
    how_much: "few_sessions",
    recommendation: "yes_with_caveats",
    what_makes_it_great: "A friend swears by the 10am slot.",
    caveat: "",
    caveat_answered: true,
    who_for: null,
    who_not_for: null,
    price_band: null,
    price_unit: null,
    worth_it: null,
    follow_up_ok: false,
    tip_text: null,
    status: "pending_review",
    confidence: 0.44,
    provenance: "parent_submitted",
    contributor: { id: "c2", name: "Sample Parent B" },
    is_test: false,
    created_at: now,
  },
  {
    id: "t1",
    kind: "tip",
    place: {
      id: "p3",
      name: "Camp registration timing",
      venue: null,
      neighborhoods: [],
      age_bands: ["grade"],
      freshness_state: "fresh",
      last_confirmed_at: now,
      validated_count: 0,
    },
    firsthand: true,
    child_age_at_time: [6],
    last_there: "current",
    how_much: null,
    recommendation: "yes",
    what_makes_it_great: null,
    caveat: null,
    /** The caveat step was never reached — different from answering "nothing". */
    caveat_answered: false,
    who_for: null,
    who_not_for: null,
    price_band: null,
    price_unit: null,
    worth_it: null,
    follow_up_ok: true,
    tip_text: "Sign up the week registration opens or you'll be waitlisted.",
    status: "approved",
    confidence: null,
    provenance: "parent_submitted",
    contributor: { id: "c1", name: "Sample Parent A" },
    is_test: false,
    created_at: now,
  },
];

export const sampleCaregivers: CaregiverRow[] = [
  {
    id: "g1",
    first_name: "Rosa",
    last_initial: "R",
    type: "regular_part_time",
    good_with_bands: ["baby", "toddler"],
    strengths: ["calm_with_shy", "reliable", "no_screens"],
    good_fit_for: ["first_time_parents", "regular_schedule"],
    consent_status: "mentioned",
    active: false,
    discoverable: false,
    introducible: false,
    consent_evidence: null,
    invite_sent_by_parent: false,
    hire_again: "yes",
    review_hold: false,
    hold_reasons: [],
    has_restricted_notes: false,
    caveat: "Books up early in the summer.",
    nomination_status: "pending_review",
    contributor_reference_opt_in: "yes",
    needs_horizon: "6_months",
    needs_change_type: "fewer_hours",
    recontact_ok: true,
    pay_band: "22_26",
    pay_benchmark_consent: true,
    nominations: 2,
    provenance: "parent_submitted",
    is_test: false,
    created_at: now,
  },
  {
    id: "g2",
    first_name: "Marta",
    last_initial: "K",
    type: "occasional_sitting",
    good_with_bands: ["preschool", "grade"],
    strengths: ["plays_actively", "drives"],
    good_fit_for: ["occasional_nights"],
    /** The parent sent the invite themselves — as far as their action can go. */
    consent_status: "invited",
    active: false,
    discoverable: false,
    introducible: false,
    consent_evidence: null,
    invite_sent_by_parent: true,
    hire_again: "yes",
    review_hold: false,
    hold_reasons: [],
    has_restricted_notes: false,
    caveat: null,
    nomination_status: "pending_review",
    contributor_reference_opt_in: "maybe",
    needs_horizon: "no_change",
    needs_change_type: null,
    recontact_ok: false,
    pay_band: "18_22",
    pay_benchmark_consent: false,
    nominations: 1,
    provenance: "parent_submitted",
    is_test: false,
    created_at: now,
  },
  {
    id: "g3",
    first_name: "Dana",
    last_initial: "S",
    type: "before_after_school",
    good_with_bands: ["grade"],
    strengths: ["homework"],
    good_fit_for: ["school_runs"],
    consent_status: "mentioned",
    active: false,
    discoverable: false,
    introducible: false,
    consent_evidence: null,
    invite_sent_by_parent: false,
    /** Hesitant, so the card is held and the invite step was never offered. */
    hire_again: "hesitant",
    review_hold: true,
    hold_reasons: ["hire_again_hesitant", "hesitation_reason"],
    has_restricted_notes: true,
    caveat: null,
    nomination_status: "pending_review",
    contributor_reference_opt_in: "no",
    needs_horizon: null,
    needs_change_type: null,
    recontact_ok: false,
    pay_band: null,
    pay_benchmark_consent: false,
    nominations: 1,
    provenance: "parent_submitted",
    is_test: false,
    created_at: now,
  },
  {
    id: "g4",
    first_name: "Aida",
    last_initial: "M",
    type: "full_time",
    good_with_bands: ["baby", "toddler", "preschool"],
    strengths: ["newborns", "cooks", "bilingual"],
    good_fit_for: ["work_from_home"],
    consent_status: "consented",
    /** Consented and active: the only combination an answer may use. */
    active: true,
    discoverable: true,
    introducible: false,
    consent_evidence: {
      method: "in_person",
      note: "Said yes at the co-op pickup; Janet witnessed it.",
      at: now,
    },
    invite_sent_by_parent: true,
    hire_again: "yes",
    review_hold: false,
    hold_reasons: [],
    has_restricted_notes: false,
    caveat: "No evenings.",
    nomination_status: "approved",
    contributor_reference_opt_in: "yes",
    needs_horizon: "12_months",
    needs_change_type: "role_ending",
    recontact_ok: true,
    pay_band: "26_32",
    pay_benchmark_consent: true,
    nominations: 3,
    provenance: "parent_submitted",
    is_test: false,
    created_at: now,
  },
];

/** Served one at a time by the `restricted_note` resource, never inside a list. */
export const sampleRestrictedNote: RestrictedNote = {
  id: "rn1",
  nomination_id: "g3",
  kind: "hesitation_reason",
  body:
    "Sample only. In production this is the parent's own words, shown to nobody " +
    "outside this screen and never summarized by a model.",
  created_at: now,
};

export const sampleDuplicates: DuplicateCandidate[] = [
  {
    key: "rosa-r",
    score: 0.86,
    reason: ["same first name + initial", "overlapping ages", "same neighborhood"],
    members: [
      {
        id: "g1",
        first_name: "Rosa",
        last_initial: "R",
        type: "regular_part_time",
        neighborhood: "south-pasadena",
      },
      {
        id: "g5",
        first_name: "Rosa",
        last_initial: "R",
        type: "occasional_sitting",
        neighborhood: "south-pasadena",
      },
    ],
  },
];

export const samplePendingOptions: PendingOptionRow[] = [
  {
    id: "o1",
    market_id: "pasadena",
    category: "schools",
    submitted_value: "Sierra Vista Co-op",
    submitted_by: { id: "c1", name: "Sample Parent A" },
    occurrences: 3,
    status: "pending",
    created_at: now,
  },
  {
    id: "o2",
    market_id: "pasadena",
    category: "parent_groups",
    submitted_value: "Altadena dads WhatsApp",
    submitted_by: { id: "c2", name: "Sample Parent B" },
    occurrences: 1,
    status: "pending",
    created_at: now,
  },
];

export const sampleFlags: FlagRow[] = [
  {
    id: "f1",
    severity: "escalation",
    reason: "high_stakes_demand",
    excerpt: "Sample only — a question about a child's safety.",
    field: "question_text",
    subject: { kind: "demand_signal", id: "d3", title: "A closing question" },
    contributor: { id: "c2", name: "Sample Parent B" },
    status: "open",
    confidence: null,
    created_at: now,
  },
  {
    id: "f2",
    severity: "review",
    reason: "caregiver_review_hold",
    excerpt: "hire_again_hesitant, hesitation_reason",
    field: null,
    subject: { kind: "caregiver_nomination", id: "g3", title: "Dana S." },
    contributor: { id: "c1", name: "Sample Parent A" },
    status: "open",
    confidence: null,
    created_at: now,
  },
  {
    id: "f3",
    severity: "review",
    reason: "possible_duplicate_place",
    excerpt: "Little Maestros — similar to an existing row",
    field: "name",
    subject: { kind: "place", id: "p1", title: "Little Maestros" },
    contributor: null,
    status: "open",
    confidence: 0.72,
    created_at: now,
  },
];

export const sampleDemand: DemandRow[] = [
  {
    id: "d1",
    question_text: "Summer camps for a 5-year-old that aren't a fortune.",
    category: "camps",
    sensitivity: "ordinary",
    requires_human_review: false,
    status: "open",
    contributor: { id: "c1", name: "Sample Parent A" },
    is_test: false,
    created_at: now,
  },
  {
    id: "d2",
    question_text: "Sample only — something a parent wouldn't post in a group chat.",
    category: "the_emotional_side",
    sensitivity: "peer_support",
    requires_human_review: true,
    status: "open",
    contributor: { id: "c2", name: "Sample Parent B" },
    is_test: false,
    created_at: now,
  },
  {
    id: "d3",
    question_text: "Sample only — a health, legal or safety question.",
    category: "health_legal_safety",
    sensitivity: "high_stakes",
    requires_human_review: true,
    status: "open",
    contributor: { id: "c2", name: "Sample Parent B" },
    is_test: false,
    created_at: now,
  },
];

export const sampleFounding: FoundingRow[] = [
  {
    id: "c2",
    name: "Sample Parent B",
    phone_masked: "••• ••• 0093",
    neighborhood: "altadena",
    child_birth_years: [2019],
    school: "Field Elementary",
    invited_by: null,
    arrived_via: "school-pta",
    submissions: { activities: 2, caregivers: 0, places: 0, tips: 0 },
    checklist: {
      verified: true,
      has_neighborhood: true,
      has_children: true,
      allowance_ok: true,
      /** One short of the two the client requires. */
      qualifying_approved: 1,
      caregiver_approved: 0,
    },
    status: "pending_founding",
    created_at: now,
  },
  {
    id: "c5",
    name: "Sample Parent C",
    phone_masked: "••• ••• 7741",
    neighborhood: "sierra-madre",
    child_birth_years: [2022, 2018],
    school: "Sierra Madre Elementary",
    invited_by: null,
    arrived_via: "pasadena-moms-fb",
    submissions: { activities: 3, caregivers: 1, places: 1, tips: 0 },
    checklist: {
      verified: true,
      has_neighborhood: true,
      has_children: true,
      allowance_ok: true,
      qualifying_approved: 2,
      caregiver_approved: 1,
    },
    status: "pending_founding",
    created_at: now,
  },
];

export const sampleAudit: AuditRow[] = [
  {
    id: "au1",
    at: now,
    user: "janet",
    action: "caregiver.consent",
    resource: "caregiver",
    resource_id: "g4",
    before: { consent_status: "invited" },
    after: { consent_status: "consented", evidence: { method: "in_person" } },
  },
  {
    id: "au2",
    at: now,
    user: "andrii",
    action: "contribution.approve",
    resource: "place_contribution",
    resource_id: "a1",
    before: { status: "pending_review" },
    after: { status: "approved" },
  },
  {
    id: "au3",
    at: now,
    user: "janet",
    action: "founding.founding",
    resource: "person",
    resource_id: "c1",
    before: { founding: "pending_founding" },
    after: { founding: "founding" },
  },
];
